### PR TITLE
Feat:  modals added

### PR DESCRIPTION
**Pull request by aryan-13**
Two types of modals added:
-one without buttons
-one with action buttons.

modals

### CODE REVIEW

**Comment by Kavita539** [comment]
The UI looks good. Went through the code, naming convention is good and overall structure too. Overall looks good, can merge.

**Review by omgaikwad — COMMENTED** [review]
Code looks good to me!

**Review by omgaikwad — COMMENTED** [review]
Code looks good to me!

**Review by Vivek-Py — APPROVED** [review]
Looks good, you can merge!

**Pull request merged**
